Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models
{
    public class Course
    {
       [Key]
        public int C_courseID { get; set; }
       
        public string C_courseNumber { get; set; }
       
        public string C_courseName { get; set; }
   
        public string C_courseDescription { get; set; }
    }
}

Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models
{
    public class Instructor
    {
       [Key]
        public string I_instructorID { get; set; }       
        public string I_firstName { get; set; }     
        public string I_lastName { get; set; }      
        public string I_emailAddress { get; set; }
        [ForeignKey("Course")]
        public int? C_courseID { get; set; }
        public Course Course { get; set; }
    }
}

Models/ModelsDto/CourseDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models.ModelsDto
{
    public class CourseDto
    {
        [DisplayName("Course Identification")]
        public int C_courseID { get; set; }
        [DisplayName("Course Number")]
        public string C_courseNumber { get; set; }
        [DisplayName("Course Name")]
        public string C_courseName { get; set; }
        [DisplayName("Course Description")]
        public string C_courseDescription { get; set; }
    }
}

Models/ModelsDto/InstructorDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models.ModelsDto
{
    public class InstructorDto
    {
        [DisplayName("Indentification  Number")]
        public  string I_instructorID { get; set; }
        [DisplayName("First Name")]
        public string I_firstName { get; set; }
        [DisplayName("Last Name")]
        public string I_lastName { get; set; }
        [DisplayName(" Email Address")]
        public  string I_emailAddress { get; set; }
        [DisplayName(" Course Identification")]
        public int? C_courseID { get; set; }


       

    }
}

Models/ModelsDto/StudentDto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models.ModelsDto
{
    public class StudentDto
    {
        [DisplayName("Student Identification")]
         public int S_studentId { get; set; }
        [DisplayName("First Name")]
        public string S_firstName { get; set; }
        [DisplayName("Last Name")]
        public string S_lastName { get; set; }
        [DisplayName("Email Address")]
        public string S_EmailAddress { get; set; }
        [DisplayName(" Contact Number")]
        public string S_phoneNumber { get; set; }



    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Models
{
    public class Student
    {
       [Key]
        public int S_studentId { get; set; }
        public string S_firstName { get; set; }
        public string S_lastName { get; set; }
        public string S_EmailAddress { get; set; }

        public string S_phoneNumber { get; set; }



    }
}

Controllers/CourseController.cs
using CourseRegistration.Controllers.Data.Interfaces;
using CourseRegistration.Models.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepo _repo;

        public CourseController(ICourseRepo repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            return View(_repo.GetAllCourses());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CourseDto input)
        {
            _repo.CreateCourse(input);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            
            return View(_repo.GetCourse(id));
        }
        [HttpPost]
        public IActionResult Update(CourseDto input)
        {
            _repo.UpdateCourse(input);
            return RedirectToAction("Index");



        }



        }
}

Controllers/HomeController.cs
using CourseRegistration.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

Controllers/InstructorController.cs
using CourseRegistration.Controllers.Data.Interfaces;
using CourseRegistration.Models.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IInstructorRepo _repo1;

        public InstructorController(IInstructorRepo repo1)
        {
            _repo1 = repo1;
        }

        public IActionResult Index()
        {
            return View(_repo1.GetAllInstructor());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(InstructorDto input)
        {
            _repo1.CreateInstructor(input);
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }



        [HttpPost]
        public IActionResult Update(InstructorDto input)
        {
            _repo1.UpdateInstructor(input);
            return RedirectToAction("Index");
        }


    }
}

Controllers/StudentController.cs
using CourseRegistration.Controllers.Data.Interfaces;
using CourseRegistration.Models.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CourseRegistration.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepo _repo2;

        public StudentController(IStudentRepo repo2)
        {
            _repo2 = repo2;
        }
        public IActionResult Index()
        {
            return View(_repo2.GetAllStudent());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(StudentDto input)
        {
            _repo2.CreateStudent(input);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(_repo2.GetStudent(id));
        }
        [HttpPost]
        public IActionResult Update(StudentDto input)
        {
            _repo2.UpdateStudent(input);
            return RedirectToAction("Index");
        }

    }
}

Views/Course/Create.cshtml
@model CourseRegistration.Models.ModelsDto.CourseDto

@{
    ViewData["Title"] = "Create";
}


<h4>Create New Courses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="C_courseID" class="control-label"></label>
                <input asp-for="C_courseID" class="form-control" />
                <span asp-validation-for="C_courseID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="C_courseNumber" class="control-label"></label>
                <input asp-for="C_courseNumber" class="form-control" />
                <span asp-validation-for="C_courseNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="C_courseName" class="control-label"></label>
                <input asp-for="C_courseName" class="form-control" />
                <span asp-validation-for="C_courseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="C_courseDescription" class="control-label"></label>
                <input asp-for="C_courseDescription" class="form-control" />
                <span asp-validation-for="C_courseDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Course/Index.cshtml
@model IEnumerable<CourseRegistration.Models.ModelsDto.CourseDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.C_courseID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C_courseNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C_courseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C_courseDescription)
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.C_courseID)
            </td>
            <td><a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="ShowCourseInfo('@item.C_courseID')">
                @Html.DisplayFor(modelItem => item.C_courseNumber)
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.C_courseName)
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.C_courseDescription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id = item.C_courseID }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<script>
    functionShowCourseInfo(id)
    {
        console.log(id + 'id');
    };

</script>

Views/Course/Update.cshtml
@model CourseRegistration.Models.ModelsDto.CourseDto

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>CourseDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="C_courseID" class="control-label"></label>
                <input asp-for="C_courseID" class="form-control" />
                <span asp-validation-for="C_courseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="C_courseNumber" class="control-label"></label>
                <input asp-for="C_courseNumber" class="form-control" />
                <span asp-validation-for="C_courseNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="C_courseName" class="control-label"></label>
                <input asp-for="C_courseName" class="form-control" />
                <span asp-validation-for="C_courseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="C_courseDescription" class="control-label"></label>
                <input asp-for="C_courseDescription" class="form-control" />
                <span asp-validation-for="C_courseDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Instructor/Create.cshtml
@model CourseRegistration.Models.ModelsDto.InstructorDto

@{
    ViewData["Title"] = "Create";
}



<h4> Create New Instructors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="I_instructorID" class="control-label"></label>
                <input asp-for="I_instructorID" class="form-control" />
                <span asp-validation-for="I_instructorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_firstName" class="control-label"></label>
                <input asp-for="I_firstName" class="form-control" />
                <span asp-validation-for="I_firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_lastName" class="control-label"></label>
                <input asp-for="I_lastName" class="form-control" />
                <span asp-validation-for="I_lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_emailAddress" class="control-label"></label>
                <input asp-for="I_emailAddress" class="form-control" />
                <span asp-validation-for="I_emailAddress" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="C_courseID" class="control-label"></label>
                <input asp-for="C_courseID" class="form-control" />
                <span asp-validation-for="C_courseID" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Instructor/Index.cshtml
@model IEnumerable<CourseRegistration.Models.ModelsDto.InstructorDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.I_instructorID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.I_firstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.I_lastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.I_emailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.C_courseID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.I_instructorID)
            </td>
            <td><a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"  onclick="ShowInstructorInfo('@item.I_instructorID')">
                @Html.DisplayFor(modelItem => item.I_firstName)</a>
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.I_lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.I_emailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.C_courseID)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id=item.I_instructorID }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Views/Instructor/Update.cshtml
@model CourseRegistration.Models.ModelsDto.InstructorDto

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>InstructorDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="I_instructorID" class="control-label"></label>
                <input asp-for="I_instructorID" class="form-control" />
                <span asp-validation-for="I_instructorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_firstName" class="control-label"></label>
                <input asp-for="I_firstName" class="form-control" />
                <span asp-validation-for="I_firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_lastName" class="control-label"></label>
                <input asp-for="I_lastName" class="form-control" />
                <span asp-validation-for="I_lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="I_emailAddress" class="control-label"></label>
                <input asp-for="I_emailAddress" class="form-control" />
                <span asp-validation-for="I_emailAddress" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="C_courseID" class="control-label"></label>
                <input asp-for="C_courseID" class="form-control" />
                <span asp-validation-for="C_courseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseRegistration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseRegistration</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CourseRegistration - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model CourseRegistration.Models.ModelsDto.StudentDto

@{
    ViewData["Title"] = "Create";
}


<h4>New Student Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="S_studentId" class="control-label"></label>
                <input asp-for="S_studentId" class="form-control" />
                <span asp-validation-for="S_studentId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="S_firstName" class="control-label"></label>
                <input asp-for="S_firstName" class="form-control" />
                <span asp-validation-for="S_firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_lastName" class="control-label"></label>
                <input asp-for="S_lastName" class="form-control" />
                <span asp-validation-for="S_lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_EmailAddress" class="control-label"></label>
                <input asp-for="S_EmailAddress" class="form-control" />
                <span asp-validation-for="S_EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_phoneNumber" class="control-label"></label>
                <input asp-for="S_phoneNumber" class="form-control" />
                <span asp-validation-for="S_phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Student/Index.cshtml
@model IEnumerable<CourseRegistration.Models.ModelsDto.StudentDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.S_studentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.S_firstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.S_lastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.S_EmailAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.S_phoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.S_studentId)
            </td>
            <td>
                <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick='@item.S_studentId'>
                @Html.DisplayFor(modelItem => item.S_firstName)</a>
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.S_lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.S_EmailAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.S_phoneNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Update", new { id= item.S_studentId }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

Views/Student/Update.cshtml
@model CourseRegistration.Models.ModelsDto.StudentDto

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>StudentDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="S_studentId" class="control-label"></label>
                <input asp-for="S_studentId" class="form-control" />
                <span asp-validation-for="S_studentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_firstName" class="control-label"></label>
                <input asp-for="S_firstName" class="form-control" />
                <span asp-validation-for="S_firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_lastName" class="control-label"></label>
                <input asp-for="S_lastName" class="form-control" />
                <span asp-validation-for="S_lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_EmailAddress" class="control-label"></label>
                <input asp-for="S_EmailAddress" class="form-control" />
                <span asp-validation-for="S_EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="S_phoneNumber" class="control-label"></label>
                <input asp-for="S_phoneNumber" class="form-control" />
                <span asp-validation-for="S_phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}